### ISSUE TITLE
Call to undefined function TMS\GuzzleHttp\choose_handler()

### ISSUE THREAD

**Issue by redochka** [tamara-solution/opencart#2]
Updating  from Tamarapay version 1.8.5 to 1.8.6 broke the checkout with the following error:

```
Uncaught Error: Call to undefined function TMS\GuzzleHttp\choose_handler() in /var/www/redacted.com/upload/system/library/tamara/vendor/guzzlehttp/guzzle/src/
HandlerStack.php:39
Stack trace:
#0 /var/www/redacted.com/upload/system/library/tamara/vendor/guzzlehttp/guzzle/src/Client.php(64): TMS\GuzzleHttp\HandlerStack::create()
#1 /var/www/redacted.com/upload/system/library/tamara/vendor/tamara-solution/php-sdk/src/Tamara/HttpClient/GuzzleHttpAdapter.php(35): TMS\GuzzleHttp\Client->__construct()
#2 /var/www/redacted.com/upload/system/library/tamara/vendor/tamara-solution/php-sdk/src/Tamara/HttpClient/AdapterFactory.php(13): TMS\Tamara\HttpClient\GuzzleHttpAdapter->__construct(30, N
ULL)
#3 /var/www/redacted.com/upload/system/library/tamara/vendor/tamara-solution/php-sdk/src/Tamara/Configuration.php(102): TMS\Tamara\HttpClient\AdapterFactory::create(30, NULL)
#4 /var/www/redacted.com/upload/system/library/tamara/vendor/tamara-solution/php-sdk/src/Tamara/Configuration.php(66): TMS\Tamara\Configuration->createDefau in /var/www/redacted.com/upload/
system/library/tamara/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 39
```

Opencart version 3.0.3.1

**Comment by hoaingotamara** [comment]
Hello Dear
Please contact us via the integration email thread

**Comment by hoaingotamara** [comment]
> Updating from Tamarapay version 1.8.5 to 1.8.6 broke the checkout with the following error:
> 
> ```
> Uncaught Error: Call to undefined function TMS\GuzzleHttp\choose_handler() in /var/www/redacted.com/upload/system/library/tamara/vendor/guzzlehttp/guzzle/src/
> HandlerStack.php:39
> Stack trace:
> #0 /var/www/redacted.com/upload/system/library/tamara/vendor/guzzlehttp/guzzle/src/Client.php(64): TMS\GuzzleHttp\HandlerStack::create()
> #1 /var/www/redacted.com/upload/system/library/tamara/vendor/tamara-solution/php-sdk/src/Tamara/HttpClient/GuzzleHttpAdapter.php(35): TMS\GuzzleHttp\Client->__construct()
> #2 /var/www/redacted.com/upload/system/library/tamara/vendor/tamara-solution/php-sdk/src/Tamara/HttpClient/AdapterFactory.php(13): TMS\Tamara\HttpClient\GuzzleHttpAdapter->__construct(30, N
> ULL)
> #3 /var/www/redacted.com/upload/system/library/tamara/vendor/tamara-solution/php-sdk/src/Tamara/Configuration.php(102): TMS\Tamara\HttpClient\AdapterFactory::create(30, NULL)
> #4 /var/www/redacted.com/upload/system/library/tamara/vendor/tamara-solution/php-sdk/src/Tamara/Configuration.php(66): TMS\Tamara\Configuration->createDefau in /var/www/redacted.com/upload/
> system/library/tamara/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 39
> ```
> 
> Opencart version 3.0.3.1

Hello Dear
Please contact us via the integration email thread
